[package]
name = "substring-replace"
version = "0.1.2"
edition = "2021"
description = "This crate provides developer-friendly methods to extract, insert and replace strings with character indices."
repository = "https://github.com/neilg63/substring-replace"
categories = ["text-processing", "parsing"]
license = "GPL-2.0-or-later WITH Bison-exception-2.2"

[dependencies]
